library(tidyverse)
library(forcats)
library(tibble)
library(viridis)
theme_set(theme_classic())
theme_set(theme_classic(base_size = 18))
t <- read.table("all_patients_dist_square.txt", sep = "\t", row.names = 1, header = F, comment.char = "" )
t_dist <- as.dist(t)
clustering <- hclust(t_dist, method = "average")
levels <- data.frame(level65 = cutree(clustering, h = 65), level25 = cutree(clustering, h = 25), level150 = cutree(clustering, h = 150),level500 = cutree(clustering, h = 500), level1000 = cutree(clustering, h = 1000), level6000 = cutree(clustering, h = 6000), level7000 = cutree(clustering, h = 7000))
levels <- tibble::rownames_to_column(levels, "sample_name") %>% as.tibble
write_tsv(levels, "hc_clustering.txt")
mlst <- read_tsv("../collect_meta/samples_qc_filtered_and_annotated_per_patient.txt") 
mlst_levels <- levels %>% inner_join(mlst)
majority_ST <- mlst_levels %>% group_by(level7000, ST) %>% add_count() %>% group_by(level7000) %>% arrange(-n) %>% slice(1) %>% select(ST, level7000) %>% rename(majority_ST = ST)
mlst_levels <- mlst_levels %>% inner_join(majority_ST)
mlst_levels %>% select(sample_id, sample_name,  majority_ST,ST, level7000) %>% write_tsv("hc_clustering_upgma.txt")
clusters <- sapply(seq(0, 50000, 20), function(x){cutree(clustering, h = x )})
uq_clusters <- apply(clusters, 2, function(x){length(unique(x))})
dist_vs_uq_clusters <- tibble(snp_dist = seq(0, 50000, 20), uq_clusters = uq_clusters)
dist_vs_uq_clusters %>% ggplot(aes(snp_dist, uq_clusters)) + geom_point() + geom_vline(xintercept = 7000)
ggsave("clusters_upgma_pp.png")
ggsave("clusters_upgma_pp.pdf")
